import React from 'react';
import {
  Image,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  View,
} from 'react-native';

function TurboEncabulator(props): React.JSX.Element {

  const backgroundStyle = {
    backgroundColor: '#FFFFFF',
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar
        barStyle={'light-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        <View
          style={{
            backgroundColor: '#DDDDDD',
            padding: 24,
          }}>
          <Text style={styles.title}>Turbo Encabulator</Text>
          
          <Image source={require('./turbo-encabulator.png')} />
          <Text style={styles.body}/>
          <Text style={styles.body}>For a number of years now, work has been proceeding in order to bring perfection to the crudely conceived idea of a transmission that would not only supply inverse reactive current for use in unilateral phase detractors, but would also be capable of automatically synchronizing cardinal grammeters. Such an instrument is the turbo encabulator.</Text>
          <Text style={styles.body}/>
          <Text style={styles.body}>Now basically the only new principle involved is that instead of power being generated by the relative motion of conductors and fluxes, it is produced by the modial interaction of magneto-reluctance and capacitive diractance.</Text>
          <Text style={styles.body}/>
          <Text style={styles.body}>The original machine had a base plate of pre-famulated amulite surmounted by a malleable logarithmic casing in such a way that the two spurving bearings were in a direct line with the panametric fan. The latter consisted simply of six hydrocoptic marzlevanes, so fitted to the ambifacient lunar waneshaft that side fumbling was effectively prevented.</Text>
          <Text style={styles.body}/>
          <Text style={styles.body}>The main winding was of the normal lotus-o-delta type placed in panendermic semi-boloid slots of the stator, every seventh conductor being connected by a non-reversible tremie pipe to the differential girdle spring on the “up” end of the grammeters.</Text>
          <Text style={styles.body}/>
          <Text style={styles.body}>The turbo-encabulator has now reached a high level of development, and it’s being successfully used in the operation of novertrunnions. Moreover, whenever a forescent skor motion is required, it may also be employed in conjunction with a drawn reciprocation dingle arm, to reduce sinusoidal repleneration.</Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  title: {
    fontSize: 28,
    fontWeight: '600',
    textAlign: 'center',
  },
  bold: {
    fontWeight: '700',
  },
  body: {
    fontSize: 20,
    fontWeight: '500',
  },
});

export default TurboEncabulator;